/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun answers() {
        val aoc = Main
        for(day in aoc.days) {
            day.testInput01.entries.forEach {
                entry -> assert(entry.value == day.partOne(entry.key))
            }

            day.testInput02.entries.forEach {
                entry -> assert(entry.value == day.partTwo(entry.key))
            }
        }
    }
}
