/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.File

fun partOne(input: List<String>): String {
    var dial = 50
    var score = 0


    for (move in input) {
        var dir = 0
        if (move[0] == 'L') {
            dir = -1
        } else {
            dir = 1
        }

        var by = move.substring(1).toInt()
        if(by > 99) {
            by %= 100
        }

        dial += by * dir

        if (dial > 99) {
            dial %= 100
        } else if (dial < 0) {
            dial += 100
        }

        if (dial == 0) {
            score += 1
        }
    }

    return score.toString();
}

fun partTwo(input: List<String>): String {
    var dial = 50
    var lastDial = dial
    var score = 0


    for (move in input) {
        var dir = 0
        if (move[0] == 'L') {
            dir = -1
        } else {
            dir = 1
        }

        var by = move.substring(1).toInt()
        if(by > 99) {
            score += (by / 100)
            by %= 100
        }

        lastDial = dial
        dial += by * dir

        if (dial > 99) {
            if(lastDial != 0) {
                score += 1
            }
            dial %= 100
        } else if (dial < 0) {
            if(lastDial > 0) {
                score += 1
            }
            dial += 100
        } else if (dial == 0) {
            score += 1
        }
    }

    return score.toString();
}   

fun main() {
    val file = "../input.txt"
    val lines: List<String> = File(file).readLines()

    println(">> Part One: ${partOne(lines)}")
    println(">> Part Two: ${partTwo(lines)}")
}
